apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: connect
  namespace: confluent
spec:
  build:
    onDemand:
      plugins:
        confluentHub:
          - name: kafka-connect-datagen
            owner: confluentinc
            version: 0.6.8
        locationType: confluentHub
    type: onDemand
  dependencies:
    kafka:
      bootstrapEndpoint: kafka:9071
  image:
    application: confluentinc/cp-server-connect:8.1.0
    init: confluentinc/confluent-init-container:3.1.0
  replicas: 1
---
apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: confluent
spec:
  dataVolumeCapacity: 10Gi
  dependencies:
    alertManagerClient:
      url: http://controlcenter.confluent.svc.cluster.local:9093
    connect:
      - name: connect
        url: http://connect.confluent.svc.cluster.local:8083
    kafka:
      bootstrapEndpoint: http://kafka.confluent.svc.cluster.local:9071
    ksqldb:
      - name: ksqldb
        url: http://ksqldb.confluent.svc.cluster.local:8088
    prometheusClient:
      url: http://controlcenter.confluent.svc.cluster.local:9090
    schemaRegistry:
      url: http://schemaregistry.confluent.svc.cluster.local:8081
  image:
    application: confluentinc/cp-enterprise-control-center-next-gen:2.3.0
    init: confluentinc/confluent-init-container:3.1.0
  replicas: 1
  services:
    alertmanager:
      image: confluentinc/cp-enterprise-alertmanager:2.3.0
    prometheus:
      image: confluentinc/cp-enterprise-prometheus:2.3.0
      pvc:
        dataVolumeCapacity: 10Gi
---
apiVersion: platform.confluent.io/v1beta1
kind: KRaftController
metadata:
  name: kraftcontroller
  namespace: confluent
spec:
  dataVolumeCapacity: 10G
  dependencies:
    metricsClient:
      url: http://controlcenter.confluent.svc.cluster.local:9090
  image:
    application: confluentinc/cp-server:8.1.0
    init: confluentinc/confluent-init-container:3.1.0
  replicas: 3
---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  dataVolumeCapacity: 100Gi
  dependencies:
    kRaftController:
      clusterRef:
        name: kraftcontroller
    metricsClient:
      url: http://controlcenter.confluent.svc.cluster.local:9090
  image:
    application: confluentinc/cp-server:8.1.0
    init: confluentinc/confluent-init-container:3.1.0
  replicas: 3
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestProxy
metadata:
  name: kafkarestproxy
  namespace: confluent
spec:
  dependencies:
    schemaRegistry:
      url: http://schemaregistry.confluent.svc.cluster.local:8081
  image:
    application: confluentinc/cp-kafka-rest:8.1.0
    init: confluentinc/confluent-init-container:3.1.0
  replicas: 1
---
apiVersion: platform.confluent.io/v1beta1
kind: KsqlDB
metadata:
  name: ksqldb
  namespace: confluent
spec:
  dataVolumeCapacity: 10Gi
  image:
    application: confluentinc/cp-ksqldb-server:8.1.0
    init: confluentinc/confluent-init-container:3.1.0
  replicas: 1
---
apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: schemaregistry
  namespace: confluent
spec:
  image:
    application: confluentinc/cp-schema-registry:8.1.0
    init: confluentinc/confluent-init-container:3.1.0
  replicas: 3
