apiVersion: platform.confluent.io/v1beta1
kind: SchemaExporter
metadata:
  name: schema-exporter
  namespace: confluent
spec:
  sourceCluster:
    schemaRegistryClusterRef:
      name: schemaregistry
      namespace: confluent
  destinationCluster:
    schemaRegistryRest:
      endpoint: <YOUR CCLOUD SR ENDPOINT HERE>
      authentication:
        type: basic
        basic:
          secretRef: cc-sr-credentials
  subjects: [":*:"]
  contextType: AUTO
