apiVersion: platform.confluent.io/v1beta1
kind: SchemaExporter
metadata:
  name: schema-exporter
  namespace: confluent
spec:
  sourceCluster:
    schemaRegistryClusterRef:
      name: schemaregistry
      namespace: confluent
  destinationCluster:
    schemaRegistryRest:
      endpoint: https://lsrc-2x7pq1.eu-west-1.aws.private.confluent.cloud
      authentication:
        type: basic
        basic:
          secretRef: cc-sr-credentials
  subjects: [":*:"]
  contextType: AUTO
