apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-gp3-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com # 🎯 CRITICAL: Specifies the AWS EBS CSI driver
parameters:
  type: gp3                 # EBS Volume Type: gp3 is the current best practice (20% cheaper than gp2)
  fsType: ext4              # Filesystem type (e.g., ext4, xfs)
  tagSpecification_1: "cflt_managed_by=user"
  tagSpecification_2: "cflt_manabed_id=sven"
  # In the PS account 492737776546 these are also required
  tagSpecification_3: "cflt_service=CTG"
  tagSpecification_4: "cflt_environment=devel"
  tagSpecification_5: "cflt_keep_until=2026-12-31"
reclaimPolicy: Retain       # Policy for the underlying volume after PVC deletion (Delete or Retain)
volumeBindingMode: WaitForFirstConsumer
# Recommended for EKS: The PV is only created once a Pod requests the PVC, ensuring the volume is
# created in the correct Availability Zone where the Pod is scheduled.
allowVolumeExpansion: true  # Allows volumes to be resized (requires CSI driver support)
